---
# ServiceMonitor for Pi-hole exporter metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pihole-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: pi-hole
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: kube-prometheus
spec:
  endpoints:
  - port: prometheus
    interval: 30s
    path: /metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - pi-hole
  selector:
    matchLabels:
      app.kubernetes.io/name: pi-hole
      pi.hole/role: read-write