# HTTPRoute for Home Assistant web interface (external HTTPS)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant-https-route
  namespace: home-assistant
spec:
  hostnames:
  - ha.ashishverma.dev
  parentRefs:
  - name: envoy
    namespace: envoy-gateway-system
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: home-assistant
      port: 8080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
---
# HTTPRoute for Home Assistant code-server (external HTTPS)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant-codeserver-https-route
  namespace: home-assistant
spec:
  hostnames:
  - haconfig.ashishverma.dev
  parentRefs:
  - name: envoy
    namespace: envoy-gateway-system
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: home-assistant-codeserver
      port: 12321
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
